//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLParser.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XLParser.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS
        ///ACCRINT
        ///ACCRINTM
        ///ACOS
        ///ACOSH
        ///ADDRESS
        ///AMORDEGRC
        ///AMORLINC
        ///AND
        ///AREAS
        ///ASC
        ///ASIN
        ///ASINH
        ///ATAN
        ///ATAN2
        ///ATANH
        ///AVEDEV
        ///AVERAGE
        ///AVERAGEA
        ///AVERAGEIF
        ///AVERAGEIFS
        ///BAHTTEXT
        ///BESSELI
        ///BESSELJ
        ///BESSELK
        ///BESSELY
        ///BETADIST
        ///BETAINV
        ///BIN2DEC
        ///BIN2HEX
        ///BIN2OCT
        ///BINOMDIST
        ///CALL
        ///CEILING
        ///CELL
        ///CHAR
        ///CHIDIST
        ///CHIINV
        ///CHITEST
        ///CLEAN
        ///CODE
        ///COLUMN
        ///COLUMNS
        ///COMBIN
        ///COMPLEX
        ///CONCATENATE
        ///CONFIDENCE
        ///CONVERT
        ///CORREL
        ///COS
        ///COSH
        ///COUNT
        ///COUNTA
        ///COUNTBLANK
        ///COUNTIF
        ///COUNTIFS
        ///COUPDAYBS
        ///COUPDAYS
        ///COUPDAYSNC
        ///COUPNCD
        ///C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelBuiltinFunctionList_v120 {
            get {
                return ResourceManager.GetString("ExcelBuiltinFunctionList-v120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS
        ///ACCRINT
        ///ACCRINTM
        ///ACOS
        ///ACOSH
        ///ACOT
        ///ACOTH
        ///ADDRESS
        ///AGGREGATE
        ///AMORDEGRC
        ///AMORLINC
        ///AND
        ///ARABIC
        ///AREAS
        ///ASC
        ///ASIN
        ///ASINH
        ///ATAN
        ///ATAN2
        ///ATANH
        ///AVEDEV
        ///AVERAGE
        ///AVERAGEA
        ///AVERAGEIF
        ///AVERAGEIFS
        ///BAHTTEXT
        ///BASE
        ///BESSELI
        ///BESSELJ
        ///BESSELK
        ///BESSELY
        ///BETA.DIST
        ///BETA.INV
        ///BETADIST
        ///BETAINV
        ///BIN2DEC
        ///BIN2HEX
        ///BIN2OCT
        ///BINOM.DIST
        ///BINOM.DIST.RANGE
        ///BINOM.INV
        ///BINOMDIST
        ///BITAND
        ///BITLSHIFT
        ///BITOR
        ///BITRSHIFT
        ///BITXOR
        ///CALL
        ///CEILING
        ///CEILING.MATH
        ///CEILING.PRECISE
        ///CELL
        ///CHAR
        ///CHIDIST
        ///CHIINV
        ///CHISQ.DIST
        ///CHISQ.DIST [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelBuiltinFunctionList_v1310 {
            get {
                return ResourceManager.GetString("ExcelBuiltinFunctionList_v1310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS
        ///ACCRINT
        ///ACCRINTM
        ///ACOS
        ///ACOSH
        ///ACOT
        ///ACOTH
        ///ADDRESS
        ///AGGREGATE
        ///AMORDEGRC
        ///AMORLINC
        ///AND
        ///ARABIC
        ///AREAS
        ///ASC
        ///ASIN
        ///ASINH
        ///ATAN
        ///ATAN2
        ///ATANH
        ///AVEDEV
        ///AVERAGE
        ///AVERAGEA
        ///AVERAGEIF
        ///AVERAGEIFS
        ///BAHTTEXT
        ///BASE
        ///BESSELI
        ///BESSELJ
        ///BESSELK
        ///BESSELY
        ///BETA.DIST
        ///BETA.INV
        ///BETADIST
        ///BETAINV
        ///BIN2DEC
        ///BIN2HEX
        ///BIN2OCT
        ///BINOM.DIST
        ///BINOM.DIST.RANGE
        ///BINOM.INV
        ///BINOMDIST
        ///BITAND
        ///BITLSHIFT
        ///BITOR
        ///BITRSHIFT
        ///BITXOR
        ///CALL
        ///CEILING
        ///CEILING.MATH
        ///CEILING.PRECISE
        ///CELL
        ///CHAR
        ///CHIDIST
        ///CHIINV
        ///CHISQ.DIST
        ///CHISQ.DIST [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelBuiltinFunctionList_v139 {
            get {
                return ResourceManager.GetString("ExcelBuiltinFunctionList-v139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS
        ///ACCRINT
        ///ACCRINTM
        ///ACOS
        ///ACOSH
        ///ACOT
        ///ACOTH
        ///ADDRESS
        ///AGGREGATE
        ///AMORDEGRC
        ///AMORLINC
        ///AND
        ///ARABIC
        ///AREAS
        ///ASC
        ///ASIN
        ///ASINH
        ///ATAN
        ///ATAN2
        ///ATANH
        ///AVEDEV
        ///AVERAGE
        ///AVERAGEA
        ///AVERAGEIF
        ///AVERAGEIFS
        ///BAHTTEXT
        ///BASE
        ///BESSELI
        ///BESSELJ
        ///BESSELK
        ///BESSELY
        ///BETA.DIST
        ///BETA.INV
        ///BETADIST
        ///BETAINV
        ///BIN2DEC
        ///BIN2HEX
        ///BIN2OCT
        ///BINOM.DIST
        ///BINOM.DIST.RANGE
        ///BINOM.INV
        ///BINOMDIST
        ///BITAND
        ///BITLSHIFT
        ///BITOR
        ///BITRSHIFT
        ///BITXOR
        ///CALL
        ///CEILING
        ///CEILING.MATH
        ///CEILING.PRECISE
        ///CELL
        ///CHAR
        ///CHIDIST
        ///CHIINV
        ///CHISQ.DIST
        ///CHISQ.DIST [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelBuiltinFunctionList_v141 {
            get {
                return ResourceManager.GetString("ExcelBuiltinFunctionList_v141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS
        ///ACCRINT
        ///ACCRINTM
        ///ACOS
        ///ACOSH
        ///ACOT
        ///ACOTH
        ///ADDRESS
        ///AGGREGATE
        ///AMORDEGRC
        ///AMORLINC
        ///AND
        ///ARABIC
        ///AREAS
        ///ASC
        ///ASIN
        ///ASINH
        ///ATAN
        ///ATAN2
        ///ATANH
        ///AVEDEV
        ///AVERAGE
        ///AVERAGEA
        ///AVERAGEIF
        ///AVERAGEIFS
        ///BAHTTEXT
        ///BASE
        ///BESSELI
        ///BESSELJ
        ///BESSELK
        ///BESSELY
        ///BETA.DIST
        ///BETA.INV
        ///BETADIST
        ///BETAINV
        ///BIN2DEC
        ///BIN2HEX
        ///BIN2OCT
        ///BINOM.DIST
        ///BINOM.DIST.RANGE
        ///BINOM.INV
        ///BINOMDIST
        ///BITAND
        ///BITLSHIFT
        ///BITOR
        ///BITRSHIFT
        ///BITXOR
        ///CALL
        ///CEILING
        ///CEILING.MATH
        ///CEILING.PRECISE
        ///CELL
        ///CHAR
        ///CHIDIST
        ///CHIINV
        ///CHISQ.DIST
        ///CHISQ.DIST [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelBuiltinFunctionList_v142 {
            get {
                return ResourceManager.GetString("ExcelBuiltinFunctionList_v142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS
        ///ACCRINT
        ///ACCRINTM
        ///ACOS
        ///ACOSH
        ///ACOT
        ///ACOTH
        ///ADDRESS
        ///AGGREGATE
        ///AMORDEGRC
        ///AMORLINC
        ///AND
        ///ARABIC
        ///AREAS
        ///ARRAYTOTEXT
        ///ASC
        ///ASIN
        ///ASINH
        ///ATAN
        ///ATAN2
        ///ATANH
        ///AVEDEV
        ///AVERAGE
        ///AVERAGEA
        ///AVERAGEIF
        ///AVERAGEIFS
        ///BAHTTEXT
        ///BASE
        ///BESSELI
        ///BESSELJ
        ///BESSELK
        ///BESSELY
        ///BETA.DIST
        ///BETA.INV
        ///BETADIST
        ///BETAINV
        ///BIN2DEC
        ///BIN2HEX
        ///BIN2OCT
        ///BINOM.DIST
        ///BINOM.DIST.RANGE
        ///BINOM.INV
        ///BINOMDIST
        ///BITAND
        ///BITLSHIFT
        ///BITOR
        ///BITRSHIFT
        ///BITXOR
        ///CALL
        ///CEILING
        ///CEILING.MATH
        ///CEILING.PRECISE
        ///CELL
        ///CHAR
        ///CHIDIST
        ///CHIINV
        ///CHISQ.DIS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelBuiltinFunctionList_v150 {
            get {
                return ResourceManager.GetString("ExcelBuiltinFunctionList_v150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS
        ///ACCRINT
        ///ACCRINTM
        ///ACOS
        ///ACOSH
        ///ACOT
        ///ACOTH
        ///ADDRESS
        ///AGGREGATE
        ///AMORDEGRC
        ///AMORLINC
        ///AND
        ///ARABIC
        ///AREAS
        ///ARRAYTOTEXT
        ///ASC
        ///ASIN
        ///ASINH
        ///ATAN
        ///ATAN2
        ///ATANH
        ///AVEDEV
        ///AVERAGE
        ///AVERAGEA
        ///AVERAGEIF
        ///AVERAGEIFS
        ///BAHTTEXT
        ///BASE
        ///BESSELI
        ///BESSELJ
        ///BESSELK
        ///BESSELY
        ///BETA.DIST
        ///BETA.INV
        ///BETADIST
        ///BETAINV
        ///BIN2DEC
        ///BIN2HEX
        ///BIN2OCT
        ///BINOM.DIST
        ///BINOM.DIST.RANGE
        ///BINOM.INV
        ///BINOMDIST
        ///BITAND
        ///BITLSHIFT
        ///BITOR
        ///BITRSHIFT
        ///BITXOR
        ///CALL
        ///CEILING
        ///CEILING.MATH
        ///CEILING.PRECISE
        ///CELL
        ///CHAR
        ///CHIDIST
        ///CHIINV
        ///CHISQ.DIS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelBuiltinFunctionList_v151 {
            get {
                return ResourceManager.GetString("ExcelBuiltinFunctionList_v151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS
        ///ACCRINT
        ///ACCRINTM
        ///ACOS
        ///ACOSH
        ///ACOT
        ///ACOTH
        ///ADDRESS
        ///AGGREGATE
        ///AMORDEGRC
        ///AMORLINC
        ///AND
        ///ARABIC
        ///AREAS
        ///ARRAYTOTEXT
        ///ASC
        ///ASIN
        ///ASINH
        ///ATAN
        ///ATAN2
        ///ATANH
        ///AVEDEV
        ///AVERAGE
        ///AVERAGEA
        ///AVERAGEIF
        ///AVERAGEIFS
        ///BAHTTEXT
        ///BASE
        ///BESSELI
        ///BESSELJ
        ///BESSELK
        ///BESSELY
        ///BETA.DIST
        ///BETA.INV
        ///BETADIST
        ///BETAINV
        ///BIN2DEC
        ///BIN2HEX
        ///BIN2OCT
        ///BINOM.DIST
        ///BINOM.DIST.RANGE
        ///BINOM.INV
        ///BINOMDIST
        ///BITAND
        ///BITLSHIFT
        ///BITOR
        ///BITRSHIFT
        ///BITXOR
        ///CALL
        ///CEILING
        ///CEILING.MATH
        ///CEILING.PRECISE
        ///CELL
        ///CHAR
        ///CHIDIST
        ///CHIINV
        ///CHISQ.DIS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelBuiltinFunctionList_v152 {
            get {
                return ResourceManager.GetString("ExcelBuiltinFunctionList_v152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS
        ///ACCRINT
        ///ACCRINTM
        ///ACOS
        ///ACOSH
        ///ACOT
        ///ACOTH
        ///ADDRESS
        ///AGGREGATE
        ///AMORDEGRC
        ///AMORLINC
        ///AND
        ///ARABIC
        ///AREAS
        ///ARRAYTOTEXT
        ///ASC
        ///ASIN
        ///ASINH
        ///ATAN
        ///ATAN2
        ///ATANH
        ///AVEDEV
        ///AVERAGE
        ///AVERAGEA
        ///AVERAGEIF
        ///AVERAGEIFS
        ///BAHTTEXT
        ///BASE
        ///BESSELI
        ///BESSELJ
        ///BESSELK
        ///BESSELY
        ///BETA.DIST
        ///BETA.INV
        ///BETADIST
        ///BETAINV
        ///BIN2DEC
        ///BIN2HEX
        ///BIN2OCT
        ///BINOM.DIST
        ///BINOM.DIST.RANGE
        ///BINOM.INV
        ///BINOMDIST
        ///BITAND
        ///BITLSHIFT
        ///BITOR
        ///BITRSHIFT
        ///BITXOR
        ///CALL
        ///CEILING
        ///CEILING.MATH
        ///CEILING.PRECISE
        ///CELL
        ///CHAR
        ///CHIDIST
        ///CHIINV
        ///CHISQ.DIS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelBuiltinFunctionList_v160 {
            get {
                return ResourceManager.GetString("ExcelBuiltinFunctionList_v160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS
        ///ACCRINT
        ///ACCRINTM
        ///ACOS
        ///ACOSH
        ///ACOT
        ///ACOTH
        ///ADDRESS
        ///AGGREGATE
        ///AMORDEGRC
        ///AMORLINC
        ///AND
        ///ARABIC
        ///AREAS
        ///ARRAYTOTEXT
        ///ASC
        ///ASIN
        ///ASINH
        ///ATAN
        ///ATAN2
        ///ATANH
        ///AVEDEV
        ///AVERAGE
        ///AVERAGEA
        ///AVERAGEIF
        ///AVERAGEIFS
        ///BAHTTEXT
        ///BASE
        ///BESSELI
        ///BESSELJ
        ///BESSELK
        ///BESSELY
        ///BETA.DIST
        ///BETA.INV
        ///BETADIST
        ///BETAINV
        ///BIN2DEC
        ///BIN2HEX
        ///BIN2OCT
        ///BINOM.DIST
        ///BINOM.DIST.RANGE
        ///BINOM.INV
        ///BINOMDIST
        ///BITAND
        ///BITLSHIFT
        ///BITOR
        ///BITRSHIFT
        ///BITXOR
        ///CALL
        ///CEILING
        ///CEILING.MATH
        ///CEILING.PRECISE
        ///CELL
        ///CHAR
        ///CHIDIST
        ///CHIINV
        ///CHISQ.DIS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelBuiltinFunctionList_v161 {
            get {
                return ResourceManager.GetString("ExcelBuiltinFunctionList_v161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS
        ///ACCRINT
        ///ACCRINTM
        ///ACOS
        ///ACOSH
        ///ACOT
        ///ACOTH
        ///ADDRESS
        ///AGGREGATE
        ///AMORDEGRC
        ///AMORLINC
        ///AND
        ///ARABIC
        ///AREAS
        ///ARRAYTOTEXT
        ///ASC
        ///ASIN
        ///ASINH
        ///ATAN
        ///ATAN2
        ///ATANH
        ///AVEDEV
        ///AVERAGE
        ///AVERAGEA
        ///AVERAGEIF
        ///AVERAGEIFS
        ///BAHTTEXT
        ///BASE
        ///BESSELI
        ///BESSELJ
        ///BESSELK
        ///BESSELY
        ///BETA.DIST
        ///BETA.INV
        ///BETADIST
        ///BETAINV
        ///BIN2DEC
        ///BIN2HEX
        ///BIN2OCT
        ///BINOM.DIST
        ///BINOM.DIST.RANGE
        ///BINOM.INV
        ///BINOMDIST
        ///BITAND
        ///BITLSHIFT
        ///BITOR
        ///BITRSHIFT
        ///BITXOR
        ///CALL
        ///CEILING
        ///CEILING.MATH
        ///CEILING.PRECISE
        ///CELL
        ///CHAR
        ///CHIDIST
        ///CHIINV
        ///CHISQ.DIS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelBuiltinFunctionList_v162 {
            get {
                return ResourceManager.GetString("ExcelBuiltinFunctionList_v162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS
        ///ACCRINT
        ///ACCRINTM
        ///ACOS
        ///ACOSH
        ///ACOT
        ///ACOTH
        ///ADDRESS
        ///AGGREGATE
        ///AMORDEGRC
        ///AMORLINC
        ///AND
        ///ARABIC
        ///AREAS
        ///ARRAYTOTEXT
        ///ASC
        ///ASIN
        ///ASINH
        ///ATAN
        ///ATAN2
        ///ATANH
        ///AVEDEV
        ///AVERAGE
        ///AVERAGEA
        ///AVERAGEIF
        ///AVERAGEIFS
        ///BAHTTEXT
        ///BASE
        ///BESSELI
        ///BESSELJ
        ///BESSELK
        ///BESSELY
        ///BETA.DIST
        ///BETA.INV
        ///BETADIST
        ///BETAINV
        ///BIN2DEC
        ///BIN2HEX
        ///BIN2OCT
        ///BINOM.DIST
        ///BINOM.DIST.RANGE
        ///BINOM.INV
        ///BINOMDIST
        ///BITAND
        ///BITLSHIFT
        ///BITOR
        ///BITRSHIFT
        ///BITXOR
        ///CALL
        ///CEILING
        ///CEILING.MATH
        ///CEILING.PRECISE
        ///CELL
        ///CHAR
        ///CHIDIST
        ///CHIINV
        ///CHISQ.DIS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelBuiltinFunctionList_v163 {
            get {
                return ResourceManager.GetString("ExcelBuiltinFunctionList_v163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS
        ///ACCRINT
        ///ACCRINTM
        ///ACOS
        ///ACOSH
        ///ACOT
        ///ACOTH
        ///ADDRESS
        ///AGGREGATE
        ///AMORDEGRC
        ///AMORLINC
        ///AND
        ///ARABIC
        ///AREAS
        ///ARRAYTOTEXT
        ///ASC
        ///ASIN
        ///ASINH
        ///ATAN
        ///ATAN2
        ///ATANH
        ///AVEDEV
        ///AVERAGE
        ///AVERAGEA
        ///AVERAGEIF
        ///AVERAGEIFS
        ///BAHTTEXT
        ///BASE
        ///BESSELI
        ///BESSELJ
        ///BESSELK
        ///BESSELY
        ///BETA.DIST
        ///BETA.INV
        ///BETADIST
        ///BETAINV
        ///BIN2DEC
        ///BIN2HEX
        ///BIN2OCT
        ///BINOM.DIST
        ///BINOM.DIST.RANGE
        ///BINOM.INV
        ///BINOMDIST
        ///BITAND
        ///BITLSHIFT
        ///BITOR
        ///BITRSHIFT
        ///BITXOR
        ///CALL
        ///CEILING
        ///CEILING.MATH
        ///CEILING.PRECISE
        ///CELL
        ///CHAR
        ///CHIDIST
        ///CHIINV
        ///CHISQ.DIS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcelBuiltinFunctionList_v170 {
            get {
                return ResourceManager.GetString("ExcelBuiltinFunctionList_v170", resourceCulture);
            }
        }
    }
}
